import "pe"

rule DetectDotNetExecutables
{
    meta:
        description = "Detect executables generated by C# or .NET - ChatGPT PROMPT: Generate a yara rule that detects executable generated by c# or dotnet."
        author = "ChatGPT"
        date = "2025-01-07"
        version = "1.0"
        yarahub_uuid = "8470c0f3-2cf3-49f8-90ba-83c588c3da68"
        yarahub_license = "CC0 1.0"
        yarahub_rule_matching_tlp = "TLP:WHITE"
        yarahub_rule_sharing_tlp = "TLP:WHITE"
        yarahub_reference_md5 = "524fca1eea0f55f1ad6281325664dcb4"
    
    strings:
        $MZ = { 4D 5A 90 00 03 00 00 00 04 00 } // MZ signature
        $PE = { 50 45 00 00 } // PE signature
        $XMLNS_SCHEMA_ASM = "schemas-microsoft-com:asm.v1" ascii wide
        $XMLNS_SCHEMA_NS = "schemas.microsoft.com" ascii wide
        $GITHUB_DEPENDENCY_LIMERBOY = "https://github.com/LimerBoy/StormKitty" ascii wide

    condition:
        $MZ and 
        $PE and 
        $XMLNS_SCHEMA_ASM and 
        $XMLNS_SCHEMA_NS and 
        $GITHUB_DEPENDENCY_LIMERBOY and 
        pe.characteristics and 
        pe.linker_version.major >= 8 
}
